# Form implementation generated from reading ui file 'D:\KLTN\QLCN\1304\generated-files/ui/new_page_summarization.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(930, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sum_wg2 = QtWidgets.QWidget(parent=Form)
        self.sum_wg2.setObjectName("sum_wg2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sum_wg2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.sum_wg2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.sum1_txt = QtWidgets.QPlainTextEdit(parent=self.sum_wg2)
        self.sum1_txt.setObjectName("sum1_txt")
        self.verticalLayout_2.addWidget(self.sum1_txt)
        self.verticalLayout.addWidget(self.sum_wg2)
        self.sum_wg1 = QtWidgets.QWidget(parent=Form)
        self.sum_wg1.setObjectName("sum_wg1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sum_wg1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sum_wg3 = QtWidgets.QWidget(parent=self.sum_wg1)
        self.sum_wg3.setMinimumSize(QtCore.QSize(0, 60))
        self.sum_wg3.setObjectName("sum_wg3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sum_wg3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.del_sum_btn = QtWidgets.QPushButton(parent=self.sum_wg3)
        self.del_sum_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.del_sum_btn.setObjectName("del_sum_btn")
        self.horizontalLayout.addWidget(self.del_sum_btn)
        spacerItem = QtWidgets.QSpacerItem(711, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sum_btn = QtWidgets.QPushButton(parent=self.sum_wg3)
        self.sum_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.sum_btn.setObjectName("sum_btn")
        self.horizontalLayout.addWidget(self.sum_btn)
        self.verticalLayout_3.addWidget(self.sum_wg3)
        self.sum2_txt = QtWidgets.QPlainTextEdit(parent=self.sum_wg1)
        self.sum2_txt.setObjectName("sum2_txt")
        self.verticalLayout_3.addWidget(self.sum2_txt)
        self.verticalLayout.addWidget(self.sum_wg1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nhập văn bản cần tóm tắt vào đây"))
        self.del_sum_btn.setText(_translate("Form", "Xóa"))
        self.sum_btn.setText(_translate("Form", "Tóm tắt"))
